```go
package main
 
import (
    "fmt"
    "os"
)
 
func Foo() error {
    var err *os.PathError = nil
    return err
}
 
func main() {
    err := Foo()
    fmt.Println(err)
    fmt.Println(err == nil)
}
```
Вывод: nil, false. Сначала инициализируется значение os.PathError со значением nil, но фактически содержит указатель на os.PathError.  